package com.pratik.job.domain;

public enum IndustryType {
    TECHNOLOGY,
    FINANCE_BANKING,
    HEALTHCARE,
    EDUCATION,
    MANUFACTURING,
    RETAIL_ECOMMERCE,
    HOSPITALITY_TOURISM,
    REAL_ESTATE,
    MEDIA_ENTERTAINMENT,
    TRANSPORTATION_LOGISTICS,
    ENERGY_UTILITIES,
    INFORMATION_TECHNOLOGY,
    AGRICULTURE,
    CONSULTING,
    LEGAL,
    TELECOMMUNICATIONS,
    AUTOMOTIVE,
    PHARMACEUTICAL,
    CONSTRUCTION,
    HUMAN_RESOURCES,
    MARKETING_ADVERTISING,
    OTHER
}
